"""
Migration 001 — Initial schema.

This file was generated by Alembic (with minor manual edits for pgvector).
Every migration has:
  - upgrade(): what to do when applying this migration (forward)
  - downgrade(): what to do when rolling back (reverse)

This is the initial migration — it creates ALL tables from scratch.
"""

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# Revision identifiers — Alembic uses these to track which migrations
# have been applied. Each revision points to its parent (down_revision).
revision = "001"
down_revision = None   # None = this is the first migration
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Enable pgvector extension — must be done BEFORE creating VECTOR columns
    # This is a one-time operation per Postgres database
    op.execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ── documents ──────────────────────────────────────────────────────────
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("document_type", sa.Text(), nullable=False),
        sa.Column("image_object_key", sa.Text(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
        sa.Column("checkpoint_id", sa.UUID(), nullable=True),
    )

    # ── extracted_fields ───────────────────────────────────────────────────
    op.create_table(
        "extracted_fields",
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("field_name", sa.Text(), primary_key=True),
        sa.Column("field_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
    )

    # ── validation_results ─────────────────────────────────────────────────
    op.create_table(
        "validation_results",
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("rule_name", sa.Text(), primary_key=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
    )

    # ── tampering_results ──────────────────────────────────────────────────
    op.create_table(
        "tampering_results",
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("check_type", sa.Text(), primary_key=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("flagged", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("detail", sa.JSON(), nullable=True),
    )

    # ── face_embeddings ────────────────────────────────────────────────────
    op.create_table(
        "face_embeddings",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("documents.id", ondelete="CASCADE"), unique=True),
        sa.Column("embedding", Vector(512), nullable=True),
        sa.Column("person_cluster_id", sa.UUID(), nullable=True),
    )
    # IVFFlat index for fast approximate nearest-neighbor search on embeddings
    # Without this, pgvector does a full table scan for every face comparison
    op.execute(
        "CREATE INDEX IF NOT EXISTS face_embedding_idx "
        "ON face_embeddings USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)"
    )

    # ── risk_scores ────────────────────────────────────────────────────────
    op.create_table(
        "risk_scores",
        sa.Column("document_id", sa.UUID(), sa.ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("band", sa.Text(), nullable=True),
        sa.Column("reasons", sa.JSON(), nullable=True),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )

    # ── audit_ledger ───────────────────────────────────────────────────────
    op.create_table(
        "audit_ledger",
        sa.Column("id", sa.UUID(), primary_key=True),
        sa.Column("sequence_num", sa.BigInteger(), unique=True, nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload_hash", sa.Text(), nullable=False),
        sa.Column("prev_record_hash", sa.Text(), nullable=False),
        sa.Column("record_hash", sa.Text(), nullable=False),
        sa.Column("officer_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
        ),
    )
    # Index on sequence_num for fast chain walks
    op.create_index("ix_audit_ledger_seq", "audit_ledger", ["sequence_num"])


def downgrade() -> None:
    """Roll back: drop all tables in reverse dependency order."""
    op.drop_table("audit_ledger")
    op.drop_table("risk_scores")
    op.drop_index("face_embedding_idx", table_name="face_embeddings")
    op.drop_table("face_embeddings")
    op.drop_table("tampering_results")
    op.drop_table("validation_results")
    op.drop_table("extracted_fields")
    op.drop_table("documents")
