import type {
  FraudGraphData,
  ValidationRuleItem,
  ClusterHistoryResponse,
} from "./types";

export const MOCK_FRAUD_GRAPH: FraudGraphData = {
  clusters: [
    {
      cluster_id: "7b2e2d1a-4122-4809-94fc-32490ab81234",
      primary_name: "VIKTOR KASPAROV",
      total_identities: 4,
      risk_score: 94.2,
      risk_band: "critical",
      flags_count: 5,
    },
    {
      cluster_id: "3e365d37-623b-40fa-8a02-1e0cdfa58799",
      primary_name: "MARCUS VERN",
      total_identities: 3,
      risk_score: 87.5,
      risk_band: "high",
      flags_count: 3,
    },
    {
      cluster_id: "9c1a8820-e2b7-49d0-9941-0f72a4128f11",
      primary_name: "ELENA ROSTOVA",
      total_identities: 2,
      risk_score: 72.0,
      risk_band: "high",
      flags_count: 2,
    },
    {
      cluster_id: "2f4091a1-7c93-4a11-b054-9a88220011bb",
      primary_name: "DAVID STERLING",
      total_identities: 2,
      risk_score: 42.0,
      risk_band: "medium",
      flags_count: 1,
    },
  ],
  nodes: [
    // Persons / Identity anchors
    {
      id: "person-1",
      label: "VIKTOR KASPAROV",
      type: "person",
      riskBand: "critical",
      clusterId: "7b2e2d1a-4122-4809-94fc-32490ab81234",
      x: 350,
      y: 220,
    },
    {
      id: "doc-1a",
      label: "RUS P789012 (Kasparov)",
      type: "document",
      riskBand: "critical",
      clusterId: "7b2e2d1a-4122-4809-94fc-32490ab81234",
      x: 200,
      y: 120,
    },
    {
      id: "doc-1b",
      label: "EST EE44901 (Kasper)",
      type: "document",
      riskBand: "critical",
      clusterId: "7b2e2d1a-4122-4809-94fc-32490ab81234",
      x: 480,
      y: 110,
    },
    {
      id: "doc-1c",
      label: "BLR B992014 (Viktor K.)",
      type: "document",
      riskBand: "high",
      clusterId: "7b2e2d1a-4122-4809-94fc-32490ab81234",
      x: 220,
      y: 330,
    },
    {
      id: "cp-del",
      label: "DEL-T3 Airport",
      type: "checkpoint",
      x: 100,
      y: 240,
    },
    {
      id: "cp-attari",
      label: "Attari Land Border",
      type: "checkpoint",
      x: 580,
      y: 250,
    },

    // Cluster 2
    {
      id: "person-2",
      label: "MARCUS VERN",
      type: "person",
      riskBand: "high",
      clusterId: "3e365d37-623b-40fa-8a02-1e0cdfa58799",
      x: 750,
      y: 400,
    },
    {
      id: "doc-2a",
      label: "ROU L982XX34 (Vern)",
      type: "document",
      riskBand: "high",
      clusterId: "3e365d37-623b-40fa-8a02-1e0cdfa58799",
      x: 640,
      y: 510,
    },
    {
      id: "doc-2b",
      label: "BGR 4018291 (Werner)",
      type: "document",
      riskBand: "medium",
      clusterId: "3e365d37-623b-40fa-8a02-1e0cdfa58799",
      x: 880,
      y: 480,
    },
    {
      id: "cp-mum",
      label: "BOM Seaport",
      type: "checkpoint",
      x: 920,
      y: 330,
    },
  ],
  links: [
    {
      source: "person-1",
      target: "doc-1a",
      label: "Face Match (98.4%)",
      severity: "low",
    },
    {
      source: "person-1",
      target: "doc-1b",
      label: "Name Collision / Alias",
      flagType: "name_mismatch_across_cluster",
      severity: "critical",
    },
    {
      source: "person-1",
      target: "doc-1c",
      label: "Doc ID Collision",
      flagType: "document_number_mismatch_across_cluster",
      severity: "high",
    },
    {
      source: "doc-1a",
      target: "cp-del",
      label: "Scanned 14:02 UTC",
    },
    {
      source: "doc-1b",
      target: "cp-attari",
      label: "Scanned 15:10 UTC (Velocity Anomaly)",
      flagType: "impossible_travel_detected",
      severity: "critical",
    },
    {
      source: "person-2",
      target: "doc-2a",
      label: "Face Match (94.1%)",
      severity: "low",
    },
    {
      source: "person-2",
      target: "doc-2b",
      label: "Alias Mismatch",
      flagType: "name_mismatch_across_cluster",
      severity: "high",
    },
    {
      source: "doc-2b",
      target: "cp-mum",
      label: "Transit 08:30 UTC",
    },
  ],
};

export const MOCK_VALIDATION_RULES: ValidationRuleItem[] = [
  {
    rule_name: "expiry_not_passed",
    description:
      "Passport expiration date must be in the future relative to current UTC date.",
    rule_type: "date_check",
    field: "expiry_date",
    condition: "> today",
    error_message: "Passport has expired.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "passport_validity_window_sufficient",
    description:
      "Passport must have at least 6 months (180 days) of validity remaining for entry.",
    rule_type: "date_check",
    field: "expiry_date",
    condition: "> today + 180d",
    error_message: "Passport has less than 6 months validity remaining.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "dob_plausibility",
    description:
      "Date of birth must be in the past and holder age must be between 0 and 125 years.",
    rule_type: "date_check",
    field: "date_of_birth",
    condition: "< today",
    error_message: "Date of birth is invalid or in the future.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "passport_number_format",
    description:
      "Passport number must match standard format (1 letter followed by 7-8 digits).",
    rule_type: "regex_format",
    field: "doc_number",
    pattern: "^[A-Z][0-9]{7,8}$",
    error_message:
      "Passport number does not conform to standard format (e.g. A1234567).",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "nationality_code_format",
    description: "Nationality must be a valid 3-letter ICAO country code.",
    rule_type: "regex_format",
    field: "nationality",
    pattern: "^[A-Z]{3}$",
    error_message: "Nationality must be a 3-letter ISO/ICAO code.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "mrz_checksum_integrity",
    description:
      "All ICAO Doc 9303 check digits across line 1 and line 2 MRZ must compute to valid mod-10 sums.",
    rule_type: "checksum",
    field: "mrz_raw",
    condition: "mod10(doc_num, dob, expiry, composite) == true",
    error_message: "MRZ check digit failure detected.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "visual_to_mrz_consistency",
    description:
      "Holder name, document number, and date of birth in OCR visual zone must match MRZ decoded data.",
    rule_type: "cross_field",
    field: "visual_zone vs mrz_zone",
    condition: "visual.doc_number == mrz.doc_number && visual.dob == mrz.dob",
    error_message: "Discrepancy between visual text and machine readable zone.",
    document_type: "passport",
    active: true,
  },
  {
    rule_name: "visa_sponsor_identifier_valid",
    description:
      "Sponsoring institution or company ID must follow regional biometric accreditation format.",
    rule_type: "regex_format",
    field: "sponsor_id",
    pattern: "^[A-Z]{2}-[0-9]{6}$",
    error_message: "Invalid visa sponsor accreditation format.",
    document_type: "visa",
    active: true,
  },
  {
    rule_name: "license_class_standard_match",
    description:
      "Driving category code must match approved Vienna Convention vehicle classifications.",
    rule_type: "regex_format",
    field: "license_class",
    pattern: "^(AM|A1|A2|A|B1|B|BE|C1|C1E|C|CE|D1|D1E|D|DE)$",
    error_message: "Unrecognized vehicle classification on driving license.",
    document_type: "driving_license",
    active: true,
  },
];

export const MOCK_CLUSTER_DETAIL: ClusterHistoryResponse = {
  person_cluster_id: "7b2e2d1a-4122-4809-94fc-32490ab81234",
  total_documents: 3,
  documents: [
    {
      document_id: "d1-8849-kasparov",
      checkpoint_type: "airport",
      checkpoint_id: "CP-DEL-T3",
      checkpoint_name: "Indira Gandhi Intl Airport T3",
      uploaded_at: "2026-08-30T14:02:11Z",
      document_type: "passport",
      name: "VIKTOR KASPAROV",
      document_number: "P7890123",
      nationality: "RUS",
      date_of_birth: "1984-04-12",
      risk_score: 94.2,
      risk_band: "critical",
      similarity: 0.985,
    },
    {
      document_id: "d2-9901-kasper",
      checkpoint_type: "land_border",
      checkpoint_id: "CP-ATTARI-01",
      checkpoint_name: "Attari Integrated Checkpost",
      uploaded_at: "2026-08-30T15:10:45Z",
      document_type: "national_id",
      name: "VIKTOR KASPER",
      document_number: "EE449012",
      nationality: "EST",
      date_of_birth: "1984-04-12",
      risk_score: 91.0,
      risk_band: "critical",
      similarity: 0.978,
    },
    {
      document_id: "d3-1120-kuznetsov",
      checkpoint_type: "sea",
      checkpoint_id: "CP-MUM-PORT",
      checkpoint_name: "Mumbai International Cruise Terminal",
      uploaded_at: "2026-08-25T09:30:00Z",
      document_type: "passport",
      name: "VALERI KUZNETSOV",
      document_number: "B9920145",
      nationality: "BLR",
      date_of_birth: "1984-04-12",
      risk_score: 82.5,
      risk_band: "high",
      similarity: 0.962,
    },
  ],
  flags: [
    {
      flag_type: "impossible_travel_detected",
      severity: "critical",
      detail:
        "Transit from Delhi T3 to Attari Border (460km) in 68 minutes is physically impossible by ground transit.",
      related_document_ids: ["d1-8849-kasparov", "d2-9901-kasper"],
      timestamp: "2026-08-30T15:10:45Z",
    },
    {
      flag_type: "name_mismatch_across_cluster",
      severity: "critical",
      detail:
        "Conflicting surnames ('KASPAROV' vs 'KASPER' vs 'KUZNETSOV') detected across 3 scans with >96% biometric similarity.",
      related_document_ids: [
        "d1-8849-kasparov",
        "d2-9901-kasper",
        "d3-1120-kuznetsov",
      ],
      timestamp: "2026-08-30T15:10:45Z",
    },
    {
      flag_type: "repeat_offender_hit",
      severity: "high",
      detail:
        "Cluster has 2 prior Critical-tier incidents flagged within the last 30 days.",
      related_document_ids: ["d1-8849-kasparov"],
      timestamp: "2026-08-30T14:02:11Z",
    },
  ],
  cross_checkpoint_risk: 0.94,
  repeat_offender_hit: true,
  highest_prior_risk_band: "critical",
  highest_prior_risk_score: 94.2,
  recommended_escalation: true,
  summary:
    "Severe multi-identity fraud syndicate detected. Subject exhibits 3 distinct national passports and identities across Land, Sea, and Air ports with impossible transit velocities.",
};
